version : '3'

services :

  nginx:
    build: requirements/nginx/
    container_name: nginx
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
  
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      args:
        - SQL_DATABASE=${SQL_DATABASE}
        - SQL_USER=${SQL_USER}
        - SQL_PASSWORD=${SQL_PASSWORD}
        - SQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
    env_file: .env
    volumes: 
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    build: requirements/wordpress
    depends_on:
      - mariadb
    restart: on-failure
    expose: 
      - "9000"
 
volumes :
  wordpress:
   driver: local
   driver_opts:
     type: 'none'
     o: 'bind'
     device: '/home/sylvain/Bureau/inception/wordpress'
 mariadb:
   driver: local
   driver_opts:
     type: 'none'
     o: 'bind'
     device: '/home/sylvain/Bureau/inception/mariadb'

etworks: 
 inception:
    driver: bridge
